import type { Metadata } from "next";
import "./globals.css";
import Sidebar from "@/app/components/ui/Sidebar/Sidebar";

export const metadata: Metadata = {
  title: "Checkmate",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-lightgray">
        <Sidebar/>
        {children}
      </body>
    </html>
  );
}
